---

version: 2

defaults: &defaults
  docker:
    - image: canonicalwebteam/dev
  environment:
    BLOG_ENABLED: True
    WEBAPP: snapcraft
  working_directory: /srv

jobs:
  python-lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install flake8
      - run:
          name: Lint webapp with Flake8
          command: flake8

workflows:
  version: 2
  build:
    jobs:
      - python-lint

---
